DROP TABLE DEPARTMENT;

DROP TABLE EMPLOYEE;

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID NUMBER(2) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(30) NOT NULL
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY(DEPARTMENT_ID);

ALTER TABLE DEPARTMENT ADD CONSTRAINT UN_DEPARTMENT_NAME UNIQUE(DEPARTMENT_NAME);

CREATE TABLE EMPLOYEE(
    REGISTRATION_ID NUMBER(5) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    EMPLOYEE_NAME VARCHAR2(60) NOT NULL,
    DEPARTMENT_ID NUMBER(2) NOT NULL,
    BIRTH_DATE DATE,
    ADMISSION_DATE DATE NOT NULL,
    SALLARY NUMBER(7, 2) NOT NULL,
    ADDRESS VARCHAR2(80)
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_REGISTRATION_ID PRIMARY KEY(REGISTRATION_ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT CK_SALLARY CHECK(SALLARY >= 1000);

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID);

ALTER TABLE EMPLOYEE ADD EMAIL VARCHAR2(60);

ALTER TABLE EMPLOYEE MODIFY EMAIL VARCHAR(100) NOT NULL;

ALTER TABLE EMPLOYEE DROP COLUMN EMAIL;

-- ALTER TABLE EMPLOYEE DROP CONSTRAINT PK_REGISTRATION_ID;

-- ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_DEPARTMENT_ID CASCADE;

-- ALTER TABLE EMPLOYEE RENAME TO FUNCTIONARY;

ALTER TABLE EMPLOYEE RENAME COLUMN ADMISSION_DATE TO ADMISSION;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

-- DELETE FROM DEPARTMENT WHERE DEPARTMENT_ID = 1;
