DROP TABLE DEPARTMENTS;

DROP TABLE EMPLOYEES;

CREATE TABLE DEPARTMENTS(
    DEPARTMENT_ID NUMBER(2) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(30) NOT NULL
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY(DEPARTMENT_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT UN_DEPARTMENT_NAME UNIQUE(DEPARTMENT_NAME);

CREATE TABLE EMPLOYEES(
    REGISTRATION_ID NUMBER(5) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
    EMPLOYEE_NAME VARCHAR2(60) NOT NULL,
    DEPARTMENT_ID NUMBER(2) NOT NULL,
    BIRTH_DATE DATE,
    ADMISSION_DATE DATE NOT NULL,
    SALLARY NUMBER(7, 2) NOT NULL,
    ADDRESS VARCHAR2(80)
);

ALTER TABLE EMPLOYEES ADD CONSTRAINT PK_REGISTRATION_ID PRIMARY KEY(REGISTRATION_ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT CK_SALLARY CHECK(SALLARY >= 1000);

ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE EMPLOYEES ADD EMAIL VARCHAR2(60);

ALTER TABLE EMPLOYEES MODIFY EMAIL VARCHAR(100) NOT NULL;

ALTER TABLE EMPLOYEES DROP COLUMN EMAIL;

-- ALTER TABLE EMPLOYEES DROP CONSTRAINT PK_REGISTRATION_ID;

-- ALTER TABLE EMPLOYEES DROP CONSTRAINT FK_DEPARTMENT_ID CASCADE;

-- ALTER TABLE EMPLOYEES RENAME TO FUNCTIONARY;

ALTER TABLE EMPLOYEES RENAME COLUMN ADMISSION_DATE TO ADMISSION;

SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

-- DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = 1;
